title: Leah Nakaima
description: Stuff that I come across and find interesting.
author: Leah Nakaima
email: leahnakaima@gmail.com
phone: (617) 453-9761
github: https://github.com/Leahnakaima
about: I am a Master in Public Policy graduate from <a href="https://www.harvard.edu/" target="_blank">Harvard.edu</a> driven by my passion for technology policy, pharmaceutical policy, market access research, health equity, and increased medicine innovation and access.
disqus_shortname: programming
google_analytics: UA-31048387-6
avatar_url: /static/img/me.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-instagram
      link: "https://www.instagram.com/leahnakaima/?hl=en"
    - icon: fa-twitter
      link: "https://twitter.com/tmjam3011"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/leah-nakaima/"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/Leahnakaima"
    - icon: fa-smartrecruiters
      link: "https://my.smartrecruiters.com/public/profiles/leah.nakaima"

share:
  twitter_username: nakleah
  # fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Blogs
      url: /blogs/
    - text: XML Feed
      url: /feed.xml
# url: "http://localhost:4000"
url: "https://tmjam.github.io/tauseef-blog"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/blogs/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
